"""topology.yaml → .env.topology 변환.

`make topology` 가 호출. stdout 으로 env 라인 출력 → 호출자가 redirect.

서비스 이름은 env 키로 쓸 때 대문자 + 하이픈 → 언더스코어:
  dro       → DRO_HOST / DRO_PORT / DRO_PUBLISH_PORT
  cm        → CM_HOST / CM_PORT / CM_PUBLISH_PORT
  actor     → ACTOR_HOST / ACTOR_PORT / ACTOR_PUBLISH_PORT
"""

from __future__ import annotations

import sys

from . import _load


def _env_key(service_name: str) -> str:
    return service_name.replace("-", "_").upper()


def main() -> None:
    data = _load()
    lines: list[str] = ["# AUTO-GENERATED by `make topology` from topology.yaml — DO NOT EDIT."]
    for name, svc in data["services"].items():
        prefix = _env_key(name)
        lines.append(f"{prefix}_HOST={svc['host']}")
        lines.append(f"{prefix}_PORT={svc['port']}")
        lines.append(f"{prefix}_PUBLISH_PORT={svc['host_publish_port']}")
    sys.stdout.write("\n".join(lines) + "\n")


if __name__ == "__main__":
    main()
