"""via:image knob → `<KNOB>_TARGET` env 라인 (compose build.target 보간용).

`venezia_topology.export_env` 미러. compose 가
`build.target: ${<KNOB>_TARGET:?…}`(부재/빈값 fail-loud) 로 소비
(CHUNK 3.0: `make up`→`_deploy_env` 가 `.env.deploy` emit + `--env-file` 주입).
actor mock stage = 3.0, dro mock stage = CHUNK 4 (둘 다 구현).
"""

from __future__ import annotations

import os
import sys
from typing import Any

from .loader import load_knobs, load_profile, validate_profile
from .model import KnobsSchema


def export_targets(knobs: KnobsSchema, profile: dict[str, Any]) -> list[str]:
    """via:image knob 마다 `<KNOB>_TARGET=production|mock` 라인 (fake → mock)."""
    lines: list[str] = ["# AUTO-GENERATED by `make deploy` — DO NOT EDIT."]
    for name, spec in knobs.knobs.items():
        if spec.realize.via != "image":
            continue
        val = profile.get(name, spec.default)
        lines.append(f"{name.upper()}_TARGET={'mock' if val == 'fake' else 'production'}")
    return lines


def main() -> None:
    knobs = load_knobs(os.getenv("DEPLOYMENT_KNOBS", "@deployment/knobs.yaml"))
    profile = load_profile(os.getenv("DEPLOYMENT_FILE", "@deployment/profile.stack.yaml"))
    validate_profile(profile, knobs)
    sys.stdout.write("\n".join(export_targets(knobs, profile)) + "\n")


if __name__ == "__main__":
    main()
